services:
  mysql:
    container_name: paga-ai-db
    image: 'mysql:8.0.40'
    environment:
      - 'MYSQL_DATABASE=paga_ai'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=app'
    ports:
      - '3306:3306'
