services:
  mysql:
    container_name: paga-ai-db
    image: 'postgres:17.3-alpine3.21'
    environment:
      - 'POSTGRES_DB=paga_ai'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - ~/git/docker:/var/lib/postgresql/data


